image: node:16.13.0 # Käytetään node Docker-imagea, jossa npm on valmiiksi asennettuna

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile # Asennetaan riippuvuudet
    - yarn build:prod # Buildataan projekti

lint:
  stage: test
  script:
    - yarn lint # Suoritetaan lint

test:
  stage: test
  script:
    - yarn test:unit # Suoritetaan testit
