stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Running build..."

lint:
  stage: test
  script:
    - echo "Running lint..."

test:
  stage: test
  script:
    - echo "Running tests..."
