
stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - yarn install --frozen-lockfile
    - yarn build:prod

test:
  stage: test
  image: node:latest
  script:
    - yarn install --frozen-lockfile
    - yarn lint
    
deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
