stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
