image: node:16.13.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile # Asennetaan riippuvudet
    - yarn build # Buildataan projekti
  artifacts: # Ladataan node_modulet artifakteihin
    paths:
      - node_modules/
    expire_in: 1 hour # Tunnin kuluttua artifakti poistetaan

lint:
  stage: test
  dependencies: # Riippuu build-jobista -> Artifaktit haetaan build-jobilta tälle jobille
    - build
  script:
    - yarn lint # Suoritetaan lint

test:
  stage: test
  dependencies: # Riippuu build-jobista -> Artifaktit haetaan build-jobilta tälle jobille
    - build
  script:
    - yarn test:unit # Suoritetaan testit

deploy:
  stage: deploy
  only:
    - master
  script:
    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
