image: node:16.13.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile
    - yarn build:prod
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

test:
  stage: test
  dependencies:
    - build
  script:
    - yarn lint
    
deploy:
  stage: deploy
  only:
    - master
  script:
    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master