image: node:16.13.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile # Asennetaan riippuvudet
    - yarn build # Buildataan projekti

lint:
  stage: test
  script:
    - yarn lint # Suoritetaan lint

test:
  stage: test
  script:
    - yarn test:unit # Suoritetaan testit
