name: Build and test

on:
  push:
    branches-ignore: 
      - 'master'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - name: Install dependencies
      run: yarn install --prefer-offline --frozen-lockfile
    - name: Run build
      run: yarn build:prod
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Run ESLint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      - name: Run tests
        run: yarn test:unit
