name: Build and test

on: push # Määritellään milloin workflow suoritetaan

jobs:
  build:
    runs-on: ubuntu-latest # Määritetään millä runnerilla jobi suoritetaan
    steps:
    - uses: actions/checkout@v2 # Käytetään checkout actionia, joka checkouttaa Git repon runnerille
    - name: Install dependencies
      run: yarn
    - name: Run build
      run: yarn build:prod
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run ESLint
        run: yarn lint
