name: Build and test

on:
  push: # Pushatessa
    branches-ignore: # Paitsi jos pushattu master haaraan
      - "master"
  workflow_call: # Toisesta workflowista kutsuessa

jobs:
  build:
    runs-on: ubuntu-latest # Määritetään millä runnerilla jobi suoritetaan
    steps:
      - uses: actions/checkout@v2 # Käytetään checkout actionia, joka checkouttaa Git repon runnerille
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
  lint:
    runs-on: ubuntu-latest
    needs: build # Odotetaan, että build suoritetaan onnistuneesti, koska riiputaan siitä
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: build # Odotetaan, että build suoritetaan onnistuneesti, koska riiputaan siitä
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test:unit
