name: Deploy application

on:
  push:
    branches: [master] # Suoritetaan vain master haarassa

jobs:
  build_and_test: # M채채ritet채채n build_and_test job
    uses: f4irline/vue-images/.github/workflows/build_and_test.yml@master # Haetaan reposta master haarasta build_and_test workflow
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Haetaan koko Git-historia
      - name: Publish to Heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:master
