# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy application

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    uses: f4irline/vue-images/.github/workflows/build_and_test.yml@master
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish to Heroku
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
