name: Deploy application

on:
  push:
    branches: [ master ]

jobs:
  build_and_test: # Määritetään build_and_test job
    uses: f4irline/vue-images/.github/workflows/build_and_test.yml@master # Haetaan reposta master haarasta build_and_test workflow
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test # Riiputaan build_and_test:istä, jolloin se suoritetaan ensin
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish to Heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:master
